checks:
    php: true
filter: {  }
coding_style:
    php:
        spaces:
            around_operators:
                unary_additive: true
tools:
    php_sim: true
    php_cpd: false
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
